spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/monopoly"
    username: postgres
    password: 1337


logging:
  config: 'classpath:log4j2.yml'
